### ISSUE TITLE
TODO: Add more tests 

### ISSUE THREAD

**Issue by apseudonym** [jmpetty/Coding-Standards-Checker#3]
We have more checkboxes than tests, we should either get rid of those checkboxes or create tests that correspond to those boxes.

**Comment by apseudonym** [comment]
Specifically, we need:
BracesChecker
BinarySpaceChecker
UnarySpaceChecker

**Comment by HogieRoll** [comment]
I'll take BracesChecker if it's not taken already...

**Comment by apseudonym** [comment]
Done
